version: '3'

services:
  # MySQL
  db:
    platform: linux/amd64
    container_name: mysql8
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db-classificator
      MYSQL_USER: test
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    volumes:
      - './tools/docker-compose-mysql/docker/db/data:/var/lib/mysql'
      - './tools/docker-compose-mysql/docker/db/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './tools/docker-compose-mysql/scripts/store.sql:/docker-entrypoint-initdb.d/init-script.sql'
    networks:
      - mynetwork

  app:
    platform: linux/amd64
    container_name: thomaz-api
    build: .
    environment:
      INTERNAL_DB_USER: test
      INTERNAL_DB_PASSWD: password
      INTERNAL_DB_HOST: db
      INTERNAL_DB_PORT: 3306
      INTERNAL_DB: db-classificator
      SECRET_KEY: ywYrEL1PKqf5ZybwbVh8ovbVlNxP7qZZTpzfADvOPNg=
      JWT_SECRET: my-secret
    ports:
      - "80:8000"
    restart: on-failure
    depends_on:
      - db
    networks:
      - mynetwork
    
networks:
  mynetwork:
